[package]
name = "yaqr_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.7", features = ["cargo"] }
yaqr = { git = "https://github.com/kenf1/yaqr", version = "0.1.0" }
