[package]
name = "crop_img"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.7"
yaqr = { git = "https://github.com/kenf1/yaqr", version = "0.1.0" }
